#!/usr/bin/zsh

setxkbmap gb -option compose:ralt
sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

for f in ~/.config/bspwm/bspwmrc.d/*
do
    source "$f"
done

MONITOR=$(polybar -m|tail -1|sed -e 's/:.*$//g') polybar -c ~/.config/polybar/config top &
picom &
