#!/usr/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 1
bspc config window_gap 6

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config click_to_focus true
bspc config focus_follows_pointer false

source ~/.config/bspwm/bspwmrc.d/*

if [ -d ~/.dotconfigs/machine-specific/$(hostname)/bspwmrc.d/ ]
then
    for f in ~/.dotconfigs/machine-specific/$(hostname)/bspwmrc.d/*
    do
        source "$f"
    done
fi

SXHKD_SHELL="/usr/bin/dash" sxhkd &
polybar top &
compton &
